ci/static-checks: enforce goimports formatting
`go fmt` was invoked with `./...`. This does not look into different
modules within the current folder. So the CI missed that a file in the
tetragon-rthooks module requires linting.

The `make go-format` target didn't have this issue, since it listed all
.go files in the project root and manually piped them to the formatter.

Moreover, the Makefile uses `goimports` and the CI `go fmt` as
formatter. Since `goimports` is a superset of `go fmt` (see
https://pkg.go.dev/golang.org/x/tools/cmd/goimports), use it in both
places.

Signed-off-by: Leonard Cohnen <leonard.cohnen@gmail.com>

diff --git a/.github/workflows/static-checks.yaml b/.github/workflows/static-checks.yaml
--- a/.github/workflows/static-checks.yaml
+++ b/.github/workflows/static-checks.yaml
@@ -97,10 +97,10 @@ jobs:
           # renovate: datasource=golang-version depName=go
           go-version: '1.26.6'
 
-      - name: Check gofmt formatting
+      - name: Check Go formatting
         run: |
-          go fmt ./...
-          git diff --exit-code || (echo "gofmt checks failed. Please run 'go -w fmt ./...', and submit your changes"; exit 1)
+          make go-format
+          git diff --exit-code || (echo "Go format checks failed. Please run 'make go-format', and submit your changes"; exit 1)
 
       - name: Build clang-format Docker image
         run: docker build -f Dockerfile.clang-format -t "isovalent/clang-format:latest" .
