ci/static-checks: update go mod tidy command
Use `go mod tidy -compat=1.17`. This is needed to fix issues with the latest Viper.

Signed-off-by: William Findlay <will@isovalent.com>

diff --git a/.github/workflows/static-checks.yaml b/.github/workflows/static-checks.yaml
--- a/.github/workflows/static-checks.yaml
+++ b/.github/workflows/static-checks.yaml
@@ -43,10 +43,10 @@ jobs:
           git diff --exit-code || (echo "gofmt checks failed. Please run 'go -w fmt ./...', and submit your changes"; exit 1)
       - name: Check module vendoring
         run: |
-          go mod tidy
+          go mod tidy -compat=1.17
           go mod vendor
           go mod verify
-          test -z "$(git status --porcelain)" || (echo "Module vendoring checks failed. Please run 'go mod tidy && go mod vendor && go mod verify', and submit your changes"; exit 1)
+          test -z "$(git status --porcelain)" || (echo "Module vendoring checks failed. Please run 'go mod tidy -compat=1.17 && go mod vendor && go mod verify', and submit your changes"; exit 1)
       - name: Build clang-format Docker image
         run: |
           docker build -f Dockerfile.clang-format -t "isovalent/clang-format:latest" .
